#ifndef HARDWARE_H_
#define HARDWARE_H_

#define HARDWARE_LED_PIN D4
#define HARDWARE_PUMP_PIN D5
#define HARDWARE_BUZZER_PIN D8
#define HARDWARE_AIR_SENSOR_PIN D4
#define HARDWARE_GROUND_HUMIDITY_SENSOR_PIN A0
#define HARDWARE_GROUND_TEMP_SENSOR_PIN D5

#endif
